GUI::MainForm
LoggerClient GUI.MainForm.Logger
Mutex GUI.MainForm.files_sync
Queue<ScannedFileInfo> GUI.MainForm.files
Referenced by GUI.MainForm.ExceptionsButton_Click_1, GUI.MainForm.metroButton2_Click, GUI.MainForm.MyTimer_Tick.
List<VirusInfo> GUI.MainForm.VirusesBuffer
Referenced by GUI.MainForm.active_scan_updater_Tick, GUI.MainForm.MyTimer_Tick, GUI.MainForm.удалитьФайлToolStripMenuItem_Click.
List<VirusInfo> GUI.MainForm.InfoBuffer
Referenced by GUI.MainForm.QuarantineButton_Click_1.
Mutex GUI.MainForm.InfoBuffer_sync
Mutex GUI.MainForm.VirusesBuffer_sync
System.Windows.Forms.Timer GUI.MainForm.Updater
bool GUI.MainForm.ScanEnabled
int GUI.MainForm.CountShown
Referenced by GUI.MainForm.MyTimer_Tick.
bool GUI.MainForm.QuarantineShow
Referenced by GUI.MainForm.QuarantineButton_Click_1, GUI.APIHandlers.virusInfo.
BlowFish GUI.MainForm.cryptor
System.ComponentModel.IContainer GUI.MainForm.components
Обязательная переменная конструктора.
Referenced by GUI.MainForm.Dispose.
System.Windows.Forms.TabPage GUI.MainForm.tabPage1
MetroFramework.Controls.MetroTile GUI.MainForm.ExceptionsButton
MetroFramework.Controls.MetroTile GUI.MainForm.UpdateButton
MetroFramework.Controls.MetroTile GUI.MainForm.QuarantineButton
MetroFramework.Controls.MetroTile GUI.MainForm.settingsButton
MetroFramework.Controls.MetroTile GUI.MainForm.ScanButton
MetroFramework.Controls.MetroTile GUI.MainForm.metroTile1
System.Windows.Forms.TabPage GUI.MainForm.tabPage2
System.Windows.Forms.TabPage GUI.MainForm.tabPage3
System.Windows.Forms.TabPage GUI.MainForm.tabPage4
System.Windows.Forms.TabPage GUI.MainForm.tabPage5
System.Windows.Forms.TabPage GUI.MainForm.tabPage6
MetroFramework.Controls.MetroListView GUI.MainForm.exceptionFiles
Referenced by GUI.MainForm.metroButton1_Click, GUI.MainForm.toolStripMenuItem2_Click.
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel3
MetroFramework.Controls.MetroListView GUI.MainForm.exceptionPaths
Referenced by GUI.MainForm.metroButton1_Click, GUI.MainForm.удалитьToolStripMenuItem_Click.
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel2
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel1
MetroFramework.Controls.MetroContextMenu GUI.MainForm.ExceptionPathContextMenu
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.добавитьToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.удалитьToolStripMenuItem
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel6
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel5
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel7
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel4
MetroFramework.Controls.MetroContextMenu GUI.MainForm.MonPartitionContextMenu
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.добавитьToolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.удалитьToolStripMenuItem1
MetroFramework.Controls.MetroButton GUI.MainForm.page_exceptions_back_to_main
MetroFramework.Controls.MetroButton GUI.MainForm.saveExceptions
System.Windows.Forms.NotifyIcon GUI.MainForm.notifyIcon
MetroFramework.Controls.MetroListView GUI.MainForm.ScanObjectsList
Referenced by GUI.MainForm.metroButton2_Click, GUI.MainForm.удалитьToolStripMenuItem2_Click.
MetroFramework.Controls.MetroButton GUI.MainForm.startScanButton
System.Windows.Forms.TabPage GUI.MainForm.tabPage7
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel9
MetroFramework.Controls.MetroButton GUI.MainForm.pauseScan
Referenced by GUI.MainForm.metroButton4_Click.
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton3
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel11
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel10
MetroFramework.Controls.MetroProgressBar GUI.MainForm.progressBar
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton6
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton5
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton9
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton8
MetroFramework.Controls.MetroButton GUI.MainForm.saveSettings
MetroFramework.Controls.MetroCheckBox GUI.MainForm.metroCheckBox2
MetroFramework.Controls.MetroCheckBox GUI.MainForm.metroCheckBox1
MetroFramework.Controls.MetroContextMenu GUI.MainForm.quarantineContextMenu
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.восстановитьФайлToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.удалитьФайлToolStripMenuItem
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton10
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel15
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel14
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton11
MetroFramework.Controls.MetroContextMenu GUI.MainForm.addToScan
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.добавитьПапкуToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.добавитьФайлToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem GUI.MainForm.удалитьToolStripMenuItem2
FolderBrowserDialog GUI.MainForm.folderBrowserDialog1
OpenFileDialog GUI.MainForm.openFileDialog1
Referenced by GUI.MainForm.добавитьФайлToolStripMenuItem1_Click.
ColumnHeader GUI.MainForm.columnHeader10
ColumnHeader GUI.MainForm.columnHeader11
Timer GUI.MainForm.active_scan_updater
MetroFramework.Controls.MetroLabel GUI.MainForm.page_active_scan_scanned
MetroFramework.Controls.MetroLabel GUI.MainForm.page_active_scan_all_count
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel16
MetroFramework.Controls.MetroLabel GUI.MainForm.foundVirusesCount
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel17
TabPage GUI.MainForm.tabPage8
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel12
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel19
MetroFramework.Controls.MetroListView GUI.MainForm.metroListView4
Referenced by GUI.MainForm.metroButton12_Click, GUI.MainForm.вКарантинToolStripMenuItem_Click, GUI.MainForm.ничегоНеДелатьToolStripMenuItem_Click, GUI.MainForm.удалитьToolStripMenuItem3_Click.
MetroFramework.Controls.MetroLabel GUI.MainForm.page_scan_result_all_scanned
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel18
MetroFramework.Controls.MetroProgressSpinner GUI.MainForm.scanProgressSpinner
MetroFramework.Controls.MetroButton GUI.MainForm.ApplyingActions
MetroFramework.Controls.MetroLabel GUI.MainForm.label_scanned_file
MetroFramework.Controls.MetroLabel GUI.MainForm.page_result_text
MetroFramework.Controls.MetroContextMenu GUI.MainForm.setAction
ToolStripMenuItem GUI.MainForm.вКарантинToolStripMenuItem
ToolStripMenuItem GUI.MainForm.удалитьToolStripMenuItem3
ToolStripMenuItem GUI.MainForm.ничегоНеДелатьToolStripMenuItem
MetroFramework.Controls.MetroLabel GUI.MainForm.scanFoundResult
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel13
ColumnHeader GUI.MainForm.columnHeader6
ColumnHeader GUI.MainForm.columnHeader12
ColumnHeader GUI.MainForm.columnHeader15
ColumnHeader GUI.MainForm.columnHeader5
ColumnHeader GUI.MainForm.columnHeader13
MetroFramework.Controls.MetroContextMenu GUI.MainForm.notifyIconContextMenu
Referenced by GUI.MainForm.приостановитьЗащитуToolStripMenuItem_Click.
ToolStripMenuItem GUI.MainForm.открытьToolStripMenuItem
ToolStripMenuItem GUI.MainForm.выходToolStripMenuItem
MetroFramework.Controls.MetroLabel GUI.MainForm.latestSignatureDB_ver
MetroFramework.Controls.MetroLabel GUI.MainForm.activeSignatureDB_ver
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel20
MetroFramework.Controls.MetroContextMenu GUI.MainForm.ExceptionFileContextMenu
ToolStripMenuItem GUI.MainForm.toolStripMenuItem1
ToolStripMenuItem GUI.MainForm.toolStripMenuItem2
ColumnHeader GUI.MainForm.columnHeader7
ColumnHeader GUI.MainForm.columnHeader8
ColumnHeader GUI.MainForm.columnHeader1
ColumnHeader GUI.MainForm.columnHeader2
MetroFramework.Controls.MetroComboBox GUI.MainForm.settingsAutoAction
Referenced by GUI.MainForm.metroButton7_Click.
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel8
MetroFramework.Controls.MetroTile GUI.MainForm.progInfo
ToolStripMenuItem GUI.MainForm.приостановитьЗащитуToolStripMenuItem
MetroFramework.Controls.MetroTile GUI.MainForm.Cryptographer
TabPage GUI.MainForm.tabPage9
MetroFramework.Controls.MetroLabel GUI.MainForm.metroLabel21
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton1
ListView GUI.MainForm.cryptoTable
Referenced by GUI.MainForm.зашифроватьToolStripMenuItem_Click, GUI.MainForm.удалитьФайлToolStripMenuItem1_Click, GUI.MainForm.удалитьФайлИзЖесткогоДискаToolStripMenuItem_Click.
ColumnHeader GUI.MainForm.columnHeader3
ColumnHeader GUI.MainForm.columnHeader4
MetroFramework.Controls.MetroContextMenu GUI.MainForm.metroContextMenu1
ToolStripMenuItem GUI.MainForm.добавитьФайлToolStripMenuItem1
ToolStripMenuItem GUI.MainForm.удалитьФайлToolStripMenuItem1
ToolStripMenuItem GUI.MainForm.удалитьФайлИзЖесткогоДискаToolStripMenuItem
ToolStripMenuItem GUI.MainForm.зашифроватьToolStripMenuItem
ToolStripMenuItem GUI.MainForm.расшифроватьToolStripMenuItem
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton4
MetroFramework.Controls.MetroButton GUI.MainForm.metroButton2
SaveFileDialog GUI.MainForm.saveFileDialog1
ColumnHeader GUI.MainForm.columnHeader9
TabControl GUI.MainForm.TabControl
MetroFramework.Controls.MetroListView GUI.MainForm.quarantine_files
Referenced by GUI.MainForm.восстановитьФайлToolStripMenuItem_Click, GUI.MainForm.удалитьФайлToolStripMenuItem_Click.
GUI.MainForm.MainForm()
References GUI.Components.Configurations.Configuration.AutoAction, GUI.Components.Configurations.Configuration.ExtentionExceptions, GUI.MainForm.InitializeComponent, GUI.MainForm.MyTimer_Tick, GUI.APIHandlers.OnFoundVirus, GUI.APIHandlers.OnScannedFile, GUI.Components.Configurations.Configuration.PathExceptions, GUI.APIHandlers.virusInfo.
void GUI.MainForm.MyTimer_Tick(object sender, EventArgs e)
References GUI.Components.Configurations.Configuration.AutoAction, GUI.MainForm.CountShown, GUI.MainForm.files, GUI.Components.Configurations.Configuration.Notify_FoundVirus, GUI.Components.ScanManager.ScanManager.State, GUI.MainForm.VirusesBuffer.
Referenced by GUI.MainForm.MainForm.
void GUI.MainForm.ScanButton_Click_2(object sender, EventArgs e)
void GUI.MainForm.settingsButton_Click_1(object sender, EventArgs e)
void GUI.MainForm.QuarantineButton_Click_1(object sender, EventArgs e)
References GUI.MainForm.InfoBuffer, GUI.MainForm.QuarantineShow.
void GUI.MainForm.ExceptionsButton_Click_1(object sender, EventArgs e)
References GUI.MainForm.files.
void GUI.MainForm.UpdateButton_Click_1(object sender, EventArgs e)
void GUI.MainForm.page_exceptions_back_to_main_Click(object sender, EventArgs e)
void GUI.MainForm.metroButton9_Click(object sender, EventArgs e)
Отмена сканирования (при настройке)
void GUI.MainForm.metroButton10_Click(object sender, EventArgs e)
void GUI.MainForm.metroButton11_Click(object sender, EventArgs e)
void GUI.MainForm.metroButton8_Click(object sender, EventArgs e)
void GUI.MainForm.добавитьПапкуToolStripMenuItem_Click(object sender, EventArgs e)
void GUI.MainForm.добавитьФайлToolStripMenuItem_Click(object sender, EventArgs e)
void GUI.MainForm.metroButton2_Click(object sender, EventArgs e)
Начать сканирование
References GUI.MainForm.files, GUI.MainForm.ScanObjectsList.
Referenced by GUI.MainForm.metroButton5_Click, GUI.MainForm.metroButton6_Click.
void GUI.MainForm.tabPage7_Enter(object sender, EventArgs e)
При открытии вкладки отображения процесса сканирования
void GUI.MainForm.active_scan_updater_Tick(object sender, EventArgs e)
Обновление данных на странице процесса сканирования
References GUI.Components.ScanManager.ScanManager.CountAllFiles, GUI.Components.ScanManager.ScanManager.CountAllScannedFiles, GUI.MainForm.VirusesBuffer.
void GUI.MainForm.MainForm_FormClosing(object sender, FormClosingEventArgs e)
void GUI.MainForm.metroButton3_Click(object sender, EventArgs e)
Отменить(завершить) сканирование
void GUI.MainForm.metroButton4_Click(object sender, EventArgs e)
Приостановить сканирование
References GUI.MainForm.pauseScan.
void GUI.MainForm.metroButton12_Click(object sender, EventArgs e)
Нажатие кнопки "Выполнить действия" на вкладке результатов сканирования
References GUI.MainForm.metroListView4.
void GUI.MainForm.metroCheckBox2_CheckedChanged(object sender, EventArgs e)
void GUI.MainForm.metroCheckBox1_CheckedChanged(object sender, EventArgs e)
void GUI.MainForm.metroButton7_Click(object sender, EventArgs e)
References GUI.Components.Configurations.Configuration.AutoScanRemovableDevices, GUI.MainForm.settingsAutoAction.
void GUI.MainForm.удалитьToolStripMenuItem2_Click(object sender, EventArgs e)
References GUI.MainForm.ScanObjectsList.
void GUI.MainForm.вКарантинToolStripMenuItem_Click(object sender, EventArgs e)
References GUI.MainForm.metroListView4.
void GUI.MainForm.удалитьToolStripMenuItem3_Click(object sender, EventArgs e)
References GUI.MainForm.metroListView4.
void GUI.MainForm.ничегоНеДелатьToolStripMenuItem_Click(object sender, EventArgs e)
References GUI.MainForm.metroListView4.
void GUI.MainForm.восстановитьФайлToolStripMenuItem_Click(object sender, EventArgs e)
References API_Client_Library.VirusInfo.id, API_Client_Library.VirusInfo.inQuarantine, GUI.MainForm.quarantine_files, API_Client_Library.API.RestoreFile.
void GUI.MainForm.удалитьФайлToolStripMenuItem_Click(object sender, EventArgs e)
References API_Client_Library.API.DeleteFile, API_Client_Library.VirusInfo.id, GUI.MainForm.quarantine_files, GUI.MainForm.VirusesBuffer.
void GUI.MainForm.notifyIcon_DoubleClick(object sender, EventArgs e)
void GUI.MainForm.открытьToolStripMenuItem_Click(object sender, EventArgs e)
void GUI.MainForm.выходToolStripMenuItem_Click(object sender, EventArgs e)
void GUI.MainForm.добавитьToolStripMenuItem_Click(object sender, EventArgs e)
void GUI.MainForm.удалитьToolStripMenuItem_Click(object sender, EventArgs e)
References GUI.MainForm.exceptionPaths.
void GUI.MainForm.metroButton1_Click(object sender, EventArgs e)
References GUI.MainForm.exceptionFiles, GUI.MainForm.exceptionPaths.
void GUI.MainForm.toolStripMenuItem1_Click(object sender, EventArgs e)
void GUI.MainForm.toolStripMenuItem2_Click(object sender, EventArgs e)
References GUI.MainForm.exceptionFiles.
void GUI.MainForm.metroButton6_Click(object sender, EventArgs e)
References GUI.MainForm.metroButton2_Click.
void GUI.MainForm.metroButton5_Click(object sender, EventArgs e)
References GUI.MainForm.metroButton2_Click.
void GUI.MainForm.settingsAutoAction_SelectedIndexChanged(object sender, EventArgs e)
void GUI.MainForm.progInfo_Click(object sender, EventArgs e)
void GUI.MainForm.приостановитьЗащитуToolStripMenuItem_Click(object sender, EventArgs e)
References GUI.MainForm.notifyIconContextMenu.
void GUI.MainForm.Cryptographer_Click(object sender, EventArgs e)
void GUI.MainForm.metroButton1_Click_1(object sender, EventArgs e)
void GUI.MainForm.добавитьФайлToolStripMenuItem1_Click(object sender, EventArgs e)
References GUI.MainForm.openFileDialog1.
void GUI.MainForm.зашифроватьToolStripMenuItem_Click(object sender, EventArgs e)
References GUI.MainForm.cryptoTable.
void GUI.MainForm.metroButton2_Click_1(object sender, EventArgs e)
void GUI.MainForm.metroButton4_Click_1(object sender, EventArgs e)
void GUI.MainForm.расшифроватьToolStripMenuItem_Click(object sender, EventArgs e)
void GUI.MainForm.удалитьФайлToolStripMenuItem1_Click(object sender, EventArgs e)
References GUI.MainForm.cryptoTable.
void GUI.MainForm.удалитьФайлИзЖесткогоДискаToolStripMenuItem_Click(object sender, EventArgs e)
References GUI.MainForm.cryptoTable.
void GUI.MainForm.InitializeComponent()
Требуемый метод для поддержки конструктора — не изменяйте содержимое этого метода с помощью редактора кода.
Referenced by GUI.MainForm.MainForm.
override void GUI.MainForm.Dispose(bool disposing)
Освободить все используемые ресурсы.
disposing истинно, если управляемый ресурс должен быть удален; иначе ложно.
References GUI.MainForm.components.