MODULE__RESERVE_NEW_FILE_DETECTOR::PartitionMonitor
readonly Thread MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CommandExecuter
FileSystemWatcher [] MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileSystemWatchers
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CommandThread, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatePartitionMon, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.DisablePartitionMon, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.StopAll.
readonly Mutex MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileSystemWatchers_sync
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.DisablePartitionMon.
readonly Mutex MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatedFilesBuffer_sync
List<string> MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatedFilesBuffer
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.RemoveIfExists.
Queue<string> MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileQueue
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.Loader.
Thread MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.LoaderThread
Thread MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.BufferCleaner
static bool MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.RemoveIfExists(string path)
References MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatedFilesBuffer.
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.Loader.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreateFileEvent(object sender, FileSystemEventArgs e)
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatePartitionMon.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.ChangedFileEvent(object sender, FileSystemEventArgs e)
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatePartitionMon.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.Error(object sender, ErrorEventArgs e)
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatePartitionMon.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.Cleaner()
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.Loader()
References MODULE__RESERVE_NEW_FILE_DETECTOR.Configuration.Disable, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileQueue, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.RemoveIfExists.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CommandThread()
References MODULE__RESERVE_NEW_FILE_DETECTOR.Connector.CommandPipe, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatePartitionMon, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.DisablePartitionMon, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileSystemWatchers, MODULE__RESERVE_NEW_FILE_DETECTOR.Configuration.NamedPipeEncoding.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreatePartitionMon(string PartitionPath, string Filter)
Создать и включить FileSystemWatcher для раздела
References MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.ChangedFileEvent, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CreateFileEvent, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.Error, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileSystemWatchers.
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CommandThread.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.DisablePartitionMon(string PartitionPath)
Отключить монитор раздела
PartitionPath
References MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileSystemWatchers, MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileSystemWatchers_sync.
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.CommandThread.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.Init()
Запуск потока обработки команд и обработки фильтрации
References MODULE__RESERVE_NEW_FILE_DETECTOR.Connector.FilterInputPipe, MODULE__RESERVE_NEW_FILE_DETECTOR.Configuration.NamedPipeEncoding.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.StopAll()
Отключение всех потоков и мониторов файловой системы
References MODULE__RESERVE_NEW_FILE_DETECTOR.PartitionMonitor.FileSystemWatchers.