MODULE__SCAN::ScanTasks
Thread [] MODULE__SCAN.ScanTasks.ScanThreads
Referenced by MODULE__SCAN.ScanTasks.Init.
Queue MODULE__SCAN.ScanTasks.TaskQueue
Очередь задач сканирования
Referenced by MODULE__SCAN.Connector.commandThread, MODULE__SCAN.ScanTasks.ScanThread.
byte MODULE__SCAN.ScanTasks.ActiveScanTasks
Количество активных задач сканирования
Referenced by MODULE__SCAN.ScanTasks.ScanCompleted, MODULE__SCAN.ScanTasks.ScanStarted.
Mutex MODULE__SCAN.ScanTasks.ScanMutex
Мьютекс для сервиса сканнера
delegate void MODULE__SCAN.ScanTasks.ScanComplete(ScanTask task, ScanResult result)
delegate void MODULE__SCAN.ScanTasks.ScanStart()
static void MODULE__SCAN.ScanTasks.ScanStarted()
При старте сканирования
References MODULE__SCAN.ScanTasks.ActiveScanTasks.
Referenced by MODULE__SCAN.ScanTasks.Add.
static void MODULE__SCAN.ScanTasks.ScanCompleted(ScanTask task, ScanResult result)
Событие окончания сканирования файла
References MODULE__SCAN.ScanTasks.ActiveScanTasks.
Referenced by MODULE__SCAN.ScanTasks.Add, MODULE__SCAN.ScanTasks.ScanThread.
static void MODULE__SCAN.ScanTasks.Add(int id, string pathToFile)
Добавить задачу сканирования
pathToFile
References MODULE__SCAN.ScanTasks.ScanCompleted, MODULE__SCAN.ScanTasks.ScanStarted.
static void MODULE__SCAN.ScanTasks.ScanThread()
References MODULE__SCAN.Yara.YaraIntegration.CheckFile, MODULE__SCAN.ScanTask.file, MODULE__SCAN.Configuration.SCAN_THREAD_SLEEP, MODULE__SCAN.ScanTasks.ScanCompleted, MODULE__SCAN.ScanTasks.TaskQueue, MODULE__SCAN.Configuration.UsingYara.
Referenced by MODULE__SCAN.ScanTasks.Init.
static void MODULE__SCAN.ScanTasks.Init()
Инициализация сервиса
References MODULE__SCAN.ScanTasks.ScanThread, MODULE__SCAN.ScanTasks.ScanThreads, MODULE__SCAN.Configuration.THREAD_COUNT.