MODULE__RESERVE_NEW_FILE_DETECTOR::HardDrives
List<Drive> MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.DriveTable
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.CheckDrive, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.checkDriveSerial, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.CheckSerial, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.getDriveBySerial, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.RefreshConnectedDevices.
List<string> MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.WhiteSerialList
byte MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.countConnectedRemovableDevices
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.RemovableDeviceMonitor.Worker.
static byte MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.AddNewDrive(DriveInfo newDrive, string serialNumber)
Добавить в таблицу информацию о новом устройстве
Количество устройств в таблице
static bool MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.CheckSerial(string serialNumber)
Есть ли устройство с таким серийником в таблице
References MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.DriveTable, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.Drive.SerialNumber.
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.RemovableDeviceMonitor.Worker.
static bool MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.CheckDrive(DriveInfo drive)
Есть ли такое устройство в таблице
References MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.DriveTable, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.Drive.FileSystem, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.Drive.TotalSize, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.Drive.VolumeLabel.
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.RemovableDeviceMonitor.Worker.
static Drive MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.getDriveBySerial(string serialNumber)
Получить информацию по сериал номеру
References MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.DriveTable, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.Drive.SerialNumber.
static bool MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.checkDriveSerial(DriveInfo drive, string serial)
Проверить, принадлежит ли этому носителю такой сериал номер
true, если сериал номер равен этому накопителю
References MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.DriveTable, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.Drive.FileSystem, MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.Drive.TotalSize.
Referenced by MODULE__RESERVE_NEW_FILE_DETECTOR.RemovableDeviceMonitor.Worker.
static void MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.RefreshConnectedDevices(string[] serialNumbers)
Обновление таблицы подключенных устройств
References MODULE__RESERVE_NEW_FILE_DETECTOR.HardDrives.DriveTable.