MODULE__FILTER::Filter::FiltrationRules
List<Regex> MODULE__FILTER.Filter.FiltrationRules.OtherRules
Остальные правила
Referenced by MODULE__FILTER.Filter.FiltrationRules.Step3.
List<string> MODULE__FILTER.Filter.FiltrationRules.SimpleRules
Простые правила Если строка существует в подстроке - фильтр сработал
Referenced by MODULE__FILTER.Filter.FiltrationRules.CheckSimpleRules.
List<Regex> MODULE__FILTER.Filter.FiltrationRules.Extentions
Фильтруемые расширения ([^]+(?=.(jpg|gif|png)).)
Referenced by MODULE__FILTER.Filter.FiltrationRules.Step1.
List<Regex> MODULE__FILTER.Filter.FiltrationRules.Paths
Фильтруемые пути к файлам
Referenced by MODULE__FILTER.Filter.FiltrationRules.Step2.
List<handler> MODULE__FILTER.Filter.FiltrationRules.OtherHandlers
Прочие обработчики
Referenced by MODULE__FILTER.Filter.FiltrationRules.ApplyFilter.
delegate bool MODULE__FILTER.Filter.FiltrationRules.handler(string input)
static bool MODULE__FILTER.Filter.FiltrationRules.ApplyFilter(string input)
References MODULE__FILTER.Filter.FiltrationRules.CheckSimpleRules, MODULE__FILTER.Filter.FiltrationRules.OtherHandlers, MODULE__FILTER.Filter.FiltrationRules.Step1, MODULE__FILTER.Filter.FiltrationRules.Step2, MODULE__FILTER.Filter.FiltrationRules.Step3.
static bool MODULE__FILTER.Filter.FiltrationRules.Step1(string input)
Шаг 1 - фильтрация расширений
input
References MODULE__FILTER.Filter.FiltrationRules.Extentions.
Referenced by MODULE__FILTER.Filter.FiltrationRules.ApplyFilter.
static bool MODULE__FILTER.Filter.FiltrationRules.Step2(string input)
Шаг 2 - фильтрация путей
input
References MODULE__FILTER.Filter.FiltrationRules.Paths.
Referenced by MODULE__FILTER.Filter.FiltrationRules.ApplyFilter.
static bool MODULE__FILTER.Filter.FiltrationRules.Step3(string input)
Шаг 3 - прочие правила фильтрации
input
References MODULE__FILTER.Filter.FiltrationRules.OtherRules.
Referenced by MODULE__FILTER.Filter.FiltrationRules.ApplyFilter.
static bool MODULE__FILTER.Filter.FiltrationRules.CheckSimpleRules(string input)
References MODULE__FILTER.Filter.FiltrationRules.SimpleRules.
Referenced by MODULE__FILTER.Filter.FiltrationRules.ApplyFilter.
static void MODULE__FILTER.Filter.FiltrationRules.InitDefaultRules()
Инициализация стандартных правил
static void MODULE__FILTER.Filter.FiltrationRules.AddOtherRule(Regex rule)