Core::KernelInitializator
Process Core.KernelInitializator.GUI_Proc
Referenced by Core.KernelInitializator.Console_CancelKeyPress, Core.KernelInitializator.Main.
Configuration Core.KernelInitializator.Config
Referenced by Core.Kernel.ScanModule.ScanTasks.Init, Core.Kernel.Connectors.KernelConnectors.InitInputConnections, Core.KernelInitializator.InitKernelConfiguration, Core.Kernel.Connectors.KernelConnectors.InitOutputConnections, Core.KernelInitializator.Main.
static void Core.KernelInitializator.InitKernelConfiguration()
Инициализация конфигурации ядра
References Core.KernelInitializator.Config.
Referenced by Core.KernelInitializator.Main.
static void Core.KernelInitializator.InitKernelComponents()
Инициализация внутренних компонентов ядра ВАЖНО! Менеджер обнаруженных вирусов должен быть запущен раньше чем менеджер задач сканирования
Referenced by Core.KernelInitializator.Main.
static void Core.KernelInitializator.InitModules()
Инициализация подключаемых(DLL) модулей
References Core.Kernel.ModuleLoader.ModuleManager.Modules.
Referenced by Core.KernelInitializator.Main.
static void Core.KernelInitializator.ApplyingBasicSettings()
Применить базовые настройки модулей
Referenced by Core.KernelInitializator.Main.
static void Core.KernelInitializator.Main(string[] args)
Точка входа в ядро
args
References Core.KernelInitializator.ApplyingBasicSettings, Core.KernelInitializator.Config, Core.KernelInitializator.Console_CancelKeyPress, Core.Kernel.Configurations.Configuration.GUI_Autostart, Core.KernelInitializator.GUI_Proc, Core.KernelInitializator.InitKernelComponents, Core.KernelInitializator.InitKernelConfiguration, Core.KernelInitializator.InitModules, Core.KernelInitializator.OnCloseProcess.
static void Core.KernelInitializator.OnCloseProcess(object sender, EventArgs e)
Referenced by Core.KernelInitializator.Main.
static void Core.KernelInitializator.Console_CancelKeyPress(object sender, ConsoleCancelEventArgs e)
References Core.KernelInitializator.GUI_Proc.
Referenced by Core.KernelInitializator.Main.