GUI::APIHandlers
Form GUI.APIHandlers.f
static void GUI.APIHandlers.OnScannedFile(string file)
Если проверили файл и он не вирус
Referenced by GUI.MainForm.MainForm.
static void GUI.APIHandlers.OnFoundVirus(VirusInfo info)
Referenced by GUI.MainForm.MainForm.
static void GUI.APIHandlers.virusInfo(VirusInfo info)
При получении информации о вирусе
info
References GUI.MainForm.QuarantineShow.
Referenced by GUI.MainForm.MainForm.